[build]
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["fs", "path"]